# Production Deployment - Tasty ERP Microservices
# Deploy with: TAG=<commit-sha> docker compose -f compose.production.yml up -d
# Images from GCP Artifact Registry

services:
  # Frontend - static build served by Nginx
  frontend:
    image: us-central1-docker.pkg.dev/tastyapp-ff8b2/tastydebt/tasty-erp-frontend:${TAG:-latest}
    container_name: tasty-erp-frontend
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - web
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Waybill Service - RS.ge integration
  waybill-service:
    image: us-central1-docker.pkg.dev/tastyapp-ff8b2/tastydebt/tasty-erp-waybill:${TAG:-latest}
    container_name: tasty-erp-waybill
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SERVER_PORT=8081
      - SPRING_PROFILES_ACTIVE=production
      - FIREBASE_CREDENTIALS_PATH=/secrets/firebase-sa.json
    expose:
      - "8081"
    networks:
      - web
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: "0.5"
    volumes:
      - ./secrets/firebase-sa.json:/secrets/firebase-sa.json:ro
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Payment Service - Excel processing & reconciliation
  payment-service:
    image: us-central1-docker.pkg.dev/tastyapp-ff8b2/tastydebt/tasty-erp-payment:${TAG:-latest}
    container_name: tasty-erp-payment
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SERVER_PORT=8082
      - SPRING_PROFILES_ACTIVE=production
      - FIREBASE_CREDENTIALS_PATH=/secrets/firebase-sa.json
    expose:
      - "8082"
    networks:
      - web
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: "0.5"
    volumes:
      - ./secrets/firebase-sa.json:/secrets/firebase-sa.json:ro
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Config Service - Settings & initial debts
  config-service:
    image: us-central1-docker.pkg.dev/tastyapp-ff8b2/tastydebt/tasty-erp-config:${TAG:-latest}
    container_name: tasty-erp-config
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SERVER_PORT=8888
      - SPRING_PROFILES_ACTIVE=production
      - FIREBASE_CREDENTIALS_PATH=/secrets/firebase-sa.json
    expose:
      - "8888"
    networks:
      - web
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"
    volumes:
      - ./secrets/firebase-sa.json:/secrets/firebase-sa.json:ro
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Caddy - Reverse Proxy
  # NOTE: Caddy starts independently and handles upstream failures gracefully.
  # It will retry backend connections automatically.
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.production:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    networks:
      - web
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.25"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    depends_on:
      - frontend
      - waybill-service
      - payment-service
      - config-service

volumes:
  caddy_data:
    external: true
  caddy_config:
  caddy_logs:

networks:
  web:
    external: true
